[package]
name = "cocors_git"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
quick-error = "2.0.1"
log = "0.4.17"
